name: scontree
description: App per il progetto Scontree.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  # Grafica
  cupertino_icons: ^1.0.5
  font_awesome_flutter: ^10.1.0
  swatcher: ^0.1.0
  new_gradient_app_bar: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

  # Assets
  r_flutter: ^0.9.0
  build_runner: ^2.1.11
  # flutter pub run build_runner build --delete-conflicting-outputs


flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: Calibri
      fonts:
        - asset: assets/fonts/Calibri-Regular.ttf
        - asset: assets/fonts/Calibri-Bold.ttf
          weight: 700